"""Human-readable report and report-index helpers for bounty-core."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .finding import slugify
from .storage import REPORT_STATES, VULN_TYPES, StorageLayout


def _short(value: Any, limit: int = 160) -> str:
    text = str(value or "").strip().replace("\n", " ")
    return text[:limit] + ("…" if len(text) > limit else "")


def report_filename(finding: dict[str, Any]) -> str:
    identity = slugify(finding.get("identity") or "finding", default="finding")[:12]
    title = slugify(finding.get("title") or finding.get("asset") or identity)
    return f"{identity}-{title[:80]}.md"


def render_finding_report(finding: dict[str, Any]) -> str:
    lines = [
        f"# {finding.get('title', 'Finding')}",
        "",
        f"- **Program:** {finding.get('program', '')}",
        f"- **Family/Lane:** {finding.get('family', '')}/{finding.get('lane', '')}",
        f"- **Type:** {finding.get('type', '')}",
        f"- **Status:** {finding.get('status', '')}",
        f"- **Severity:** {finding.get('severity', '')}",
        f"- **Asset:** {finding.get('asset', '')}",
        f"- **URL:** {finding.get('url', '')}",
        f"- **Source:** {finding.get('source_repo', '')}/{finding.get('source_tool', '')}",
        f"- **Identity:** {finding.get('identity', '')}",
        "",
        "## Summary",
        "",
        str(finding.get("summary") or finding.get("description") or "Candidate finding generated by tooling. Review before submission."),
        "",
        "## Evidence",
        "",
    ]
    evidence = finding.get("evidence") or []
    if evidence:
        for item in evidence:
            lines.append(f"- {item}")
    else:
        lines.append("- No evidence entries were attached.")
    if finding.get("repro_steps"):
        lines.extend(["", "## Reproduction Steps", ""])
        for i, step in enumerate(finding.get("repro_steps") or [], start=1):
            lines.append(f"{i}. {step}")
    return "\n".join(lines).rstrip() + "\n"


def write_finding_report(layout: StorageLayout, finding: dict[str, Any]) -> Path:
    status = slugify(finding.get("status") or "raw")
    vuln_type = slugify(finding.get("type") or "unknown")
    report_dir = layout.reports_root / status / vuln_type
    report_dir.mkdir(parents=True, exist_ok=True)
    path = report_dir / report_filename(finding)
    if not path.exists():
        path.write_text(render_finding_report(finding), encoding="utf-8")
    return path


def _index_rows(findings: list[dict[str, Any]]) -> list[str]:
    rows = ["| Severity | Type | Status | Title | Asset | Source |", "|---|---|---|---|---|---|"]
    for finding in findings:
        rows.append(
            "| {severity} | {type} | {status} | {title} | `{asset}` | {source} |".format(
                severity=finding.get("severity", ""),
                type=finding.get("type", ""),
                status=finding.get("status", ""),
                title=_short(finding.get("title"), 90).replace("|", "\\|"),
                asset=_short(finding.get("asset") or finding.get("url"), 90).replace("|", "\\|"),
                source=f"{finding.get('source_repo', '')}/{finding.get('source_tool', '')}",
            )
        )
    return rows


def refresh_report_indexes(layout: StorageLayout, findings: list[dict[str, Any]]) -> dict[str, Path]:
    written: dict[str, Path] = {}
    by_status: dict[str, list[dict[str, Any]]] = {}
    by_type: dict[str, list[dict[str, Any]]] = {}
    status_type: dict[tuple[str, str], list[dict[str, Any]]] = {}

    for finding in findings:
        status = slugify(finding.get("status") or "raw")
        vuln_type = slugify(finding.get("type") or "unknown")
        by_status.setdefault(status, []).append(finding)
        by_type.setdefault(vuln_type, []).append(finding)
        status_type.setdefault((status, vuln_type), []).append(finding)

    index_root = layout.reports_root / "index"
    index_root.mkdir(parents=True, exist_ok=True)

    statuses = set(REPORT_STATES) | set(by_status)
    vuln_types = set(VULN_TYPES) | set(by_type)

    for status in sorted(statuses):
        items = by_status.get(status, [])
        path = index_root / f"{status}.md"
        path.write_text(f"# {status.title()} Findings\n\n" + "\n".join(_index_rows(items)) + "\n", encoding="utf-8")
        written[f"status/{status}"] = path

    for vuln_type in sorted(vuln_types):
        items = by_type.get(vuln_type, [])
        path = index_root / f"{vuln_type}.md"
        path.write_text(f"# {vuln_type.upper()} Findings\n\n" + "\n".join(_index_rows(items)) + "\n", encoding="utf-8")
        written[f"type/{vuln_type}"] = path

    nested_indexes = set(layout.reports_root.glob("*/*/index.md"))
    for status in statuses:
        for vuln_type in vuln_types:
            nested_indexes.add(layout.reports_root / status / vuln_type / "index.md")
    for path in nested_indexes:
        if path.parent.parent.parent == layout.reports_root:
            status = path.parent.parent.name
            vuln_type = path.parent.name
            items = status_type.get((status, vuln_type), [])
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(f"# {status.title()} {vuln_type.upper()}\n\n" + "\n".join(_index_rows(items)) + "\n", encoding="utf-8")

    for (status, vuln_type), items in status_type.items():
        path = layout.reports_root / status / vuln_type / "index.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(f"# {status.title()} {vuln_type.upper()}\n\n" + "\n".join(_index_rows(items)) + "\n", encoding="utf-8")
        written[f"status_type/{status}/{vuln_type}"] = path

    return written
